In [1]:
%load_ext autoreload
%autoreload 2

In [30]:
from fydjob.NLPFrame import NLPFrame
df = NLPFrame().df

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/alexanderherdt/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/alexanderherdt/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/alexanderherdt/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Loaded from /Users/alexanderherdt/code/mizzle-toe/find-your-dream-job/fydjob/output/nlp_frame.joblib

In [42]:
df_dict = df.head(5).to_dict()
pd.DataFrame(df_dict)

,job_id,job_title,job_text,company,location,job_info,job_link,query_text,source,tag_language,reviews,job_info_tokenized,job_text_tokenized,job_text_tokenized_titlecase,job_title_tokenized,job_text_tokenized_processed
0,1,Data Scientist / Matching Engineer (m/w/d),You are responsible for improvement of Taledo’...,Taledo,Berlin,Data Scientist / Matching Engineer (m/w/d)\nTa...,NULL,data engineer,scrape_json,en,NULL,"[data, scientist, matching, engineer, mwd, tal...","[you, are, responsible, for, improvement, of, ...","[Data, Scientist, Matching, Engineer, mwd, Tal...","[data, scientist, matching, engineer, mwd]","[responsible, improvement, taledos, search, ma..."
1,2,Senior Software Engineer - Data Platform,We are looking for a Senior Software Engineer ...,Zalando SE,Berlin,Senior Software Engineer - Data Platform\nZala...,NULL,data engineer,scrape_json,en,NULL,"[senior, software, engineer, data, platform, z...","[we, are, looking, for, a, senior, software, e...","[Senior, Software, Engineer, Data, Platform, Z...","[senior, software, engineer, data, platform]","[looking, senior, software, engineer, extensiv..."
2,3,Senior Data Engineer (m/w/t),"As a member of the Data Engineering Team, you ...",Quandoo GmbH,Berlin,Senior Data Engineer (m/w/t)\nQuandoo GmbH17 B...,NULL,data engineer,scrape_json,en,NULL,"[senior, data, engineer, mwt, quandoo, gmbh, b...","[as, a, member, of, the, data, engineering, te...","[Senior, Data, Engineer, mwt, Quandoo, GmbH, B...","[senior, data, engineer, mwt]","[member, data, engineering, team, responsible,..."
3,4,Data Engineer (w/m/d),We are digitty.io – an international start-up ...,digitty.io,Berlin,Data Engineer (w/m/d)\ndigitty.io - Berlin,NULL,data engineer,scrape_json,en,NULL,"[data, engineer, wmd, digittyio, berlin]","[we, are, digittyio, an, international, startu...","[Data, Engineer, wmd, digittyio, Berlin]","[data, engineer, wmd]","[digittyio, international, startup, headquarte..."
4,5,Data Engineer,We activate data for our clients by using stat...,Gemma Analytics,Berlin,Data Engineer\nGemma Analytics - Berlin,NULL,data engineer,scrape_json,en,NULL,"[data, engineer, gemma, analytics, berlin]","[we, activate, data, for, our, clients, by, us...","[Data, Engineer, Gemma, Analytics, Berlin]","[data, engineer]","[activate, data, client, using, stateoftheart,..."

In [93]:
import requests
url = "http://127.0.0.1:8000/"
skills = "skills"


response = requests.get(url, params = params)
### get the data frame from the api
pd.DataFrame(response.json())

,job_id,job_title,job_text,company,location,job_info,job_link,query_text,source,tag_language,reviews,job_info_tokenized,job_text_tokenized,job_text_tokenized_titlecase,job_title_tokenized,job_text_tokenized_processed
0,1,Data Scientist / Matching Engineer (m/w/d),You are responsible for improvement of Taledo’...,Taledo,Berlin,Data Scientist / Matching Engineer (m/w/d)\nTa...,NULL,data engineer,scrape_json,en,NULL,"[data, scientist, matching, engineer, mwd, tal...","[you, are, responsible, for, improvement, of, ...","[Data, Scientist, Matching, Engineer, mwd, Tal...","[data, scientist, matching, engineer, mwd]","[responsible, improvement, taledos, search, ma..."
1,2,Senior Software Engineer - Data Platform,We are looking for a Senior Software Engineer ...,Zalando SE,Berlin,Senior Software Engineer - Data Platform\nZala...,NULL,data engineer,scrape_json,en,NULL,"[senior, software, engineer, data, platform, z...","[we, are, looking, for, a, senior, software, e...","[Senior, Software, Engineer, Data, Platform, Z...","[senior, software, engineer, data, platform]","[looking, senior, software, engineer, extensiv..."
2,3,Senior Data Engineer (m/w/t),"As a member of the Data Engineering Team, you ...",Quandoo GmbH,Berlin,Senior Data Engineer (m/w/t)\nQuandoo GmbH17 B...,NULL,data engineer,scrape_json,en,NULL,"[senior, data, engineer, mwt, quandoo, gmbh, b...","[as, a, member, of, the, data, engineering, te...","[Senior, Data, Engineer, mwt, Quandoo, GmbH, B...","[senior, data, engineer, mwt]","[member, data, engineering, team, responsible,..."
3,4,Data Engineer (w/m/d),We are digitty.io – an international start-up ...,digitty.io,Berlin,Data Engineer (w/m/d)\ndigitty.io - Berlin,NULL,data engineer,scrape_json,en,NULL,"[data, engineer, wmd, digittyio, berlin]","[we, are, digittyio, an, international, startu...","[Data, Engineer, wmd, digittyio, Berlin]","[data, engineer, wmd]","[digittyio, international, startup, headquarte..."
4,5,Data Engineer,We activate data for our clients by using stat...,Gemma Analytics,Berlin,Data Engineer\nGemma Analytics - Berlin,NULL,data engineer,scrape_json,en,NULL,"[data, engineer, gemma, analytics, berlin]","[we, activate, data, for, our, clients, by, us...","[Data, Engineer, Gemma, Analytics, Berlin]","[data, engineer]","[activate, data, client, using, stateoftheart,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5876,5877,"Manager, Machine Learning",Job Description\nAlexa is Amazon's new cloud-b...,Amazon.com,SunnyvaleCA,NULL,NULL,NULL,kaggle_1,en,25907.0,[null],"[job, description, alexa, is, amazons, new, cl...",[NULL],"[manager, machine, learning]","[job, description, alexa, amazon, new, cloudba..."
5877,5878,Lead Data Scientist - Haskell,Description:\nTarget is looking for engineers ...,TARGET,SunnyvaleCA,NULL,NULL,NULL,kaggle_1,en,33275.0,[null],"[description, target, is, looking, for, engine...",[NULL],"[lead, data, scientist, haskell]","[description, target, looking, engineer, data,..."
5878,5879,Senior Data Scientist (GEC11902),Position Description\nProficient in Java or Py...,Walmart,SunnyvaleCA,NULL,NULL,NULL,kaggle_1,en,148114.0,[null],"[position, description, proficient, in, java, ...",[NULL],"[senior, data, scientist, gec]","[position, description, proficient, java, pyth..."
5879,5880,Senior Data & Applied Scientist,We are the Bing Core Relevance team responsibl...,Microsoft,SunnyvaleCA,NULL,NULL,NULL,kaggle_1,en,4618.0,[null],"[we, are, the, bing, core, relevance, team, re...",[NULL],"[senior, data, applied, scientist]","[bing, core, relevance, team, responsible, ret..."
5880,5881,"Principal Data Scientist, Deep Learning",Comcast’s Technology &amp; Product organizatio...,Comcast,SunnyvaleCA,NULL,NULL,NULL,kaggle_1,en,11610.0,[null],"[comcasts, technology, amp, product, organizat...",[NULL],"[principal, data, scientist, deep, learning]","[comcasts, technology, amp, product, organizat..."

In [102]:
params = {"query": ["python , MaTh"],
         "number": 10}

response2 = requests.get(url+skills, params = params)
response2.json()

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /skills?query=python+%2C+MaTh&number=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1202e9130>: Failed to establish a new connection: [Errno 61] Connection refused'))

In [4]:
from fydjob.Word2VecPipeline import Word2VecPipeline

pipe = Word2VecPipeline()

pipe.most_similar("python",10)

Starting Word2Vec...
Loaded model from /Users/alexanderherdt/code/mizzle-toe/find-your-dream-job/fydjob/data/models/w2v_model_baseline.model

[('r', 0.9589256644248962),
 ('scala', 0.9507297277450562),
 ('languages', 0.9489396214485168),
 ('java', 0.9475581049919128),
 ('programing', 0.9394864439964294),
 ('perl', 0.9299498796463013),
 ('matlab', 0.9242859482765198),
 ('programming', 0.9236627221107483),
 ('r.', 0.9223112463951111),
 ('php', 0.9221781492233276)]

In [8]:
pipe.most_similar("mathematics")

[('statistics', 0.966637134552002),
 ('math', 0.9631338119506836),
 ('physics', 0.9472707509994507),
 ('computer', 0.9361725449562073),
 ('science', 0.9309971332550049),
 ('economics', 0.925482988357544),
 ('scienceengineering', 0.9140040874481201),
 ('econometrics', 0.9105654358863831),
 ('fields', 0.9079679250717163),
 ('applied', 0.9071071147918701)]